/************************************************************************/
/*                                                                      */
/*    zimt - abstraction layer for SIMD programming                     */
/*                                                                      */
/*            Copyright 2023 by Kay F. Jahnke                           */
/*                                                                      */
/*    The git repository for this software is at                        */
/*                                                                      */
/*    https://github.com/kfjahnke/zimt                                  */
/*                                                                      */
/*    Please direct questions, bug reports, and contributions to        */
/*                                                                      */
/*    kfjahnke+zimt@gmail.com                                           */
/*                                                                      */
/*    Permission is hereby granted, free of charge, to any person       */
/*    obtaining a copy of this software and associated documentation    */
/*    files (the "Software"), to deal in the Software without           */
/*    restriction, including without limitation the rights to use,      */
/*    copy, modify, merge, publish, distribute, sublicense, and/or      */
/*    sell copies of the Software, and to permit persons to whom the    */
/*    Software is furnished to do so, subject to the following          */
/*    conditions:                                                       */
/*                                                                      */
/*    The above copyright notice and this permission notice shall be    */
/*    included in all copies or substantial portions of the             */
/*    Software.                                                         */
/*                                                                      */
/*    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND    */
/*    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES   */
/*    OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND          */
/*    NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT       */
/*    HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,      */
/*    WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING      */
/*    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR     */
/*    OTHER DEALINGS IN THE SOFTWARE.                                   */
/*                                                                      */
/************************************************************************/

// Another example demonstrating the direct use of zimt's 'wielding'
// code, which allows what I call 'regular' operations, an abstraction
// of array processing which uses the structure of array processing
// but not necessarily arrays as it's substrate: The processing is
// guided by an n-dimensional coordinate block which is traversed
// along parallel 1D 'lines' or 'strands' which are all parallel to
// one axis of the construct.
// This example uses a get_t functor to put together RGBA pixels
// from four separate float arrays, as you might get them 'natively'
// from some image file formats which don't store the data interleaved.
// The pixels are stored to an interleaved array.

#include <iomanip>
#include <array>
#include "../zimt.h"

// to test the transform, we add a simple pass-through functor
// which produces its' input as output. This way we can 'capture'
// the values generated by the 'get_t' object into the target array.

template < typename T , std::size_t N , std::size_t L >
struct pass_through
: public zimt::unary_functor < zimt::xel_t < T , N > ,
                               zimt::xel_t < T , N > ,
                               L >
{
  template < typename I , typename O >
  void eval ( const I & i , O & o , const std::size_t cap = 0 )
  {
    o = i ;
  }
} ;

// join_t is the 'get_t' we'll use for this example. This functor
// generates the input values to the functor. In this example we'll
// demonstrate how to use a get_t to put together RGBA pixels from
// four separate float arrays holding the channels. We want the
// get_t to do the job so that the act functor can work on rgba
// pixels as input just as if the rgba pixels had been loaded from
// an array of rgba pixels, not four separate channel arrays.

template < typename T ,     // fundamental type
           std::size_t N ,  // channel count
           std::size_t D ,  // dimensions
           std::size_t L >  // lane count
struct join_t
{
  typedef zimt::xel_t < T , N > value_t ;
  typedef zimt::simdized_type < value_t , L > value_v ;
  typedef typename value_v::value_type value_ele_v ;
  typedef zimt::xel_t < long , D > crd_t ;

  // source of data: N D-dimensional views to the fundamental type

  typedef std::array < zimt::view_t < D , T > , N > src_t ;
  src_t src ;

  zimt::xel_t < const T * , N > pickup ; // source pointers
  zimt::xel_t < long , N > stride ;      // strides of source arrays

  join_t ( const src_t & _src )
  : src ( _src )
  {
    // copy out the strides of the source arrays

    for ( int ch = 0 ; ch < N ; ch++ )
    {
      stride [ ch ] = src [ ch ] . strides [ 0 ] ;
    }
  }

  // init is used to initialize the vectorized value to the value
  // it should hold at the beginning of the peeling run. The discrete
  // coordinate 'crd' gives the location of the first value, and this
  // function infers the start value from it. Here we set the pickup
  // pointers and perform a 'regular gather' to get the first batch
  // of values. Note how we could specialize the code to use load
  // instructions instead of rgather if the stride is 1.

  void init ( value_v & v , const crd_t & crd )
  {
    for ( int ch = 0 ; ch < N ; ch++ )
    {
      pickup [ ch ] = & ( src [ ch ] [ crd ] ) ;
      v [ ch ] . rgather ( pickup [ ch ] , stride [ ch ] ) ;
    }
  }

  // initialize the scalar value using the discrete coordinate.
  // This needs to be done once after peeling, the scalar value
  // is not initialized before.

  void init ( value_t & c , const crd_t & crd )
  {
    for ( int ch = 0 ; ch < N ; ch++ )
    {
      pickup [ ch ] = & ( src [ ch ] [ crd ] ) ;
      c [ ch ] = * ( pickup [ ch ] ) ;
    }
  }

  // increase modifies it's argument to contain the next value, or
  // next vectorized value, respectively - first we increase the
  // pickup pointers, then we get the data from that location.

  void increase ( value_t & trg )
  {
    for ( int ch = 0 ; ch < N ; ch++ )
    {
      pickup [ ch ] += stride [ ch ] ;
      trg [ ch ] = * ( pickup [ ch ] ) ;
    }
  }

  void increase ( value_v & trg )
  {
    for ( int ch = 0 ; ch < N ; ch++ )
    {
      pickup [ ch ] += L * stride [ ch ] ;
      trg [ ch ] . rgather ( pickup [ ch ] , stride [ ch ] ) ;
    }
  }
} ;

int main ( int argc , char * argv[] )
{
  std::cout << std::fixed << std::showpoint
            << std::setprecision(1) ;

  zimt::bill_t bill ;

  typedef join_t < float , 4 , 2 , 16 > j_t ;
  typedef typename j_t::value_t value_t ;

  zimt::array_t < 2 , float > r ( { 1024 , 1024 } ) ;
  zimt::array_t < 2 , float > g ( { 1024 , 1024 } ) ;
  zimt::array_t < 2 , float > b ( { 1024 , 1024 } ) ;
  zimt::array_t < 2 , float > a ( { 1024 , 1024 } ) ;

  std::array < zimt::view_t < 2 , float > , 4 >
    src ( { r , g , b , a } ) ;

  j_t get_rgba ( src ) ;

  zimt::array_t < 2 , value_t > rgba ( { 1024 , 1024 } ) ;

  typedef pass_through < float , 4 , 16 > act_t ;
  zimt::norm_put_t < act_t , 2 > p ( rgba , 0 ) ;

  r [ { 101 , 203 } ] = 1.0f ;
  g [ { 101 , 203 } ] = 2.0f ;
  b [ { 101 , 203 } ] = 3.0f ;
  a [ { 101 , 203 } ] = 4.0f ;

  zimt::process < act_t , 2 > ( act_t() , rgba , bill , get_rgba , p ) ;

  std::cout << rgba [ { 100 , 203 } ] << std::endl ;
  std::cout << rgba [ { 101 , 203 } ] << std::endl ;
  std::cout << rgba [ { 102 , 203 } ] << std::endl ;
}
